### PR TITLE
catwalk + computerscientist - WR

### PR DESCRIPTION
**Pull request by wrudder**
_If you had no problems you can just leave it empty_

> How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible
catwalk 7/10

> Was there anything that you struggled with?

Found the catwalk exercise quite difficult (especially returning the cat) restarted and was fine.

> Is there any particular code you want me to look into?

> Is there anything that you'd like some further information on?

> Roughly how long did it take?
4 hours

### CODE REVIEW

**Comment by wrudder** [comment]
If you had no problems you can just leave it empty

How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible


Was there anything that you struggled with?

struggled with breaking the problem down into seperate functions an which order those go into it

Is there any particular code you want me to look into?

not sure why my last addupsum variable wasnt working for me (last one)

Is there anything that you'd like some further information on?

Roughly how long did it take?
7 hours

**Comment by CamillaCdC** [comment]
Nice work on the ATM homework! A couple of bonus things you didn't get to, but great job on getting the bulk of it working. Good work using alerts. 

Please keep your layout and indentation of your code in mind.

**Comment by wrudder** [comment]
Thanks Camilla,

Where did I go wrong for the last one I’ve got for the sum of the balances ?

Will

**Comment by CamillaCdC** [comment]
The issue is on line 67 and 69. 
67: `const $checkingBalance = parseInt($cBalance).slice(1);`
69: `const $savingsBalance = parseInt($sBalance).slice(1);`
These don't work. 

You either need to do this in two lines: 
`let $checkingBalance = $cBalance.slice(1);
$checkingBalance = parseInt($checkingBalance);`

Or, if you do it in one, put the slice inside the parseInt
67: `const $checkingBalance = parseInt($cBalance.slice(1));`

**Pull request merged**
